In [6]:
import pandas as pd # Rappresenta un array bidimensionale

In [3]:
mat = [[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14]]

In [8]:
df = pd.DataFrame(mat)

In [10]:
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14

In [19]:
elemento_particolare = df.at[1, 2] #trovare un elemento particolare all'interno dell'array bidimensionale

In [17]:
elemento_particolare

7

In [20]:
import math

In [21]:
int = 36

In [25]:
math.sin(int) #Seno

-0.9917788534431158

In [24]:
math.cos(int) #Coseno

-0.12796368962740468

In [33]:
math.factorial(int) #Fattore

371993326789901217467999448150835200000000

In [35]:
math.pi #Pi Greco

3.141592653589793

In [40]:
math.degrees(math.pi) # Converito in gradi, PiGreco = 180°

180.0

In [39]:
help(math.degrees)

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [68]:
import numpy as np #importo numpy

In [45]:
lst = [2000, 5500, 7200, 4320, 1280, 1900,
       2500, 3900, 6410, 8150, 7100, 5350]

In [69]:
vendite = np.array(lst) #creo un array di lst

In [70]:
vendita_massima = vendite.max() #valore massimo

In [51]:
vendita_massima

8150

In [71]:
vendita_minima = vendite.min() #valori minimo

In [53]:
vendita_minima

1280

In [72]:
vendite_maggiori_4999 = vendite[vendite > 4999] #vendite maggiori di 4999
numero_vendite_maggiori_4999 = len(vendite_maggiori_4999)

In [58]:
numero_vendite_maggiori_4999

6

In [73]:
vendite_minori_3000 = vendite[vendite < 3000] #vendite minori di 3000

In [63]:
vendite_minori_3000

array([2000, 1280, 1900, 2500])

In [75]:
media_vendite = vendite.mean() #media vendite mensili minori di 3000

In [66]:
media_vendite

4634.166666666667

In [77]:
fatturati_dict = {1997: 12_000, 1998: 15_000, #il dizionario memorizza dati tramite chiavi univoche
                  1999: 20_000, 2000: 23_000, 2001: 25_000,
                  2002: 17_000, 2003: 14_000, 2004: 21_000}

In [81]:
fatturati_series = pd.Series([12_000, 15_000, 20_000, #La series di panda funziiona come una array unidimensionale
                              23_000, 25_000, 17_000, 14_000, 21_000],
                             index=range(1997, 2005))

In [79]:
fatturati_dict[1997]

12000

In [80]:
fatturati_series[1997]

12000

In [82]:
# con la series è possibile effettuare operazioni vettoriali, funzioni statistiche, gestione dati mancanti, slicing, allineamento automatico dei dati

In [86]:
import numpy as np 
stipendi = np.array( [100, 200, 300, 400, 500,
                      600, 700, 800, 900, 1000] )

In [93]:
stipendi_raddoppiati = np.array([stipendio * 2 for stipendio in stipendi]) # ciclo for

In [88]:
stipendi_raddoppiati

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])

In [94]:
stipendi_raddoppiati2 = stipendi * 2 #masking

In [92]:
stipendi_raddoppiati2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])